# lazy load nvm
#export NVM_LAZY_LOAD=true

export ZDOTDIR=~/.config/zsh
export ZPLUG_HOME=~/.config/zsh/zplug

# Display MOTD on login
export ZSH_MOTD_ALWAYS

# vcxsrv display
#HOST=$(grep nameserver /etc/resolv.conf | sed 's/nameserver //')
#export DISPLAY=$HOST:0

# set xdg paths
export XDG_CACHE_HOME=~/.cache
export XDG_CONFIG_HOME=~/.config
export XDG_DATA_HOME=~/.local/share
#export XDG_RUNTIME_DIR=/run/user/$(id -u)

# use vim as the editor
export EDITOR=nvim

# try to make aws use xdg spec
export AWS_CONFIG_FILE=$XDG_CONFIG_HOME/aws/config
export AWS_CLI_HISTORY_FILE=$XDG_DATA_HOME/aws/history
export AWS_CREDENTIALS_FILE=$XDG_DATA_HOME/aws/credentials
export AWS_WEB_IDENTIFY_TOKEN_FILE=$XDG_DATA_HOME/aws/token
export AWS_SHARED_CREDENTIALS_FILE=$XDG_DATA_HOME/aws/shared-credentials

# taskwarrior
export TASKRC=$XDG_CONFIG_HOME/task/config
export TASKDATA=$XDG_DATA_HOME/task
export DOT=~/.dotfiles
export PATH=~/.local/bin:$PATH
