# Prompt setup
autoload -Uz promptinit && promptinit
source "$ZDOTDIR/prompt_noot_setup.zsh"

# Set up directory expansion
setopt autocd
setopt menucomplete
bindkey "^I" expand-or-complete

# Set up directory stack shortcuts
setopt autopushd
setopt pushdignoredups

# Append history across sessions instead of overwriting it
setopt appendhistory
setopt extendedhistory
setopt histignoredups
setopt incappendhistory

# Cycle through completion options like a menu.
setopt menucomplete

# Auto complete key-value pairs for options
setopt autoparamkeys

# Enable spelling auto correct for commands
setopt correct

# Prevent overwriting files with > unless forced with >|
setopt noclobber

# Show detailed info for background jobs
setopt longlistjobs

# Notify when a background job finishes
setopt notify

# Export variables
export XDG_CONFIG_DIR="$HOME/.config"
export XDG_DATA_DIR="$HOME/.local/share"
export DOOMWADDIR="$HOME/Wads"
export NVM_DIR="$HOME/.local/nvm"
export VIT_DIR="$XDG_CONFIG_DIR/vit"
export EDITOR="nvim"
export RUSTUP_HOME="$XDG_DATA_DIR/rustup"
export CARGO_HOME="$XDG_DATA_DIR/cargo"

# Add a new line after each command
precmd() { echo "" }

# Initialize node version manager
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

# Enable system zsh libraries. The path of these may differe from distro to distro.
# The paths provided are where Arch installs them (which is also the correct way).
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source /usr/share/zsh/plugins/zsh-history-substring-search/zsh-history-substring-search.zsh

# Aliases
alias l="exa -l"
alias ll="exa -la"
alias la="exa -alGh --icons --group-directories-first --classify --octal-permissions -S"

# Path
path+=("$CARGO_HOME/bin")
