# Start the powerline daemon
#powerline-daemon -q
#. /usr/share/powerline/bindings/zsh/powerline.zsh

# Prompt
PS1="%n@%m %1~ %# "

# this is needed for autocompletion
autoload -Uz compinit && compinit
autoload -Uz bashcompinit && bashcompinit

# load zplug
source $ZDOTDIR/zplug/init.zsh

# zplug plugins
zplug "apachler/zsh-aws"
zplug "ael-code/zsh-colored-man-pages"
zplug "unixorn/prettyping"

# Install plugins if there are plugins that have not been installed
if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi

# Source plugins and add commands to $PATH
zplug load

# aliases
alias pacinstall="pacman --color=always -Syu"
alias pacsearch="pacman --color=always -Ss"
alias pacinfo="pacman --color=always -Si"
alias sudo="sudo "
alias x="exa"
alias xa="exa -al"
alias d="mkdir"
alias r="ranger"
alias lp="lpass"
alias tw="taskwarrior-tui"
alias pbcopy="xsel --clipboard --input"
alias pbpaste="xsel --clipboard --output"
alias edit-zshrc="$EDITOR $ZDOTDIR/.zshrc"
alias edit-zshenv="$EDITOR $HOME/.zshenv"
alias edit-i3-config="$EDITOR $XDG_CONFIG_HOME/i3/config"
alias edit-kitty-config="$EDITOR $XDG_CONFIG_HOME/kitty/kitty.conf"
alias edit-polybar-config="$EDITOR $XDG_CONFIG_HOME/polybar/config.ini"
alias source-zshenv="source $HOME/.zshenv"
alias source-zshrc="source $ZDOTDIR/.zshrc"

